version: "3.9"

services: 
  web:
    container_name: "reactapp"
    build: 
      context: .
      dockerfile: "Dockerfile.dev"
    ports: 
     - "3000:3000"
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes: 
      -  /home/node/app/node_modules
      - .:/home/node/app
    
      