FROM node:alpine

#RUN mkdir /usr/app
USER node

RUN mkdir -p /home/node/app 

WORKDIR  '/home/node/app'

#ENV PATH="./node_modules/.bin:$PATH"

COPY --chown=node:node package.json ./

RUN  npm install

COPY --chown=node:node  . .

CMD ["npm","run","start"] 